# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- deploy
sast:
  stage: build
include:
- template: Security/SAST.gitlab-ci.yml

markdownlint:
  stage: build
  image: node:18.8-bullseye
  script:
  - npm install -g markdownlint-cli
  - markdownlint docs

.install_dependencies:
  before_script:
  - apt-get update && apt-get install -y graphviz=2.42.2-5 wget curl libgbm-dev libasound2 xvfb
  - Xvfb :5 -screen 0 1920x1080x8 &
  - export DISPLAY=':5.0'
  - curl -s https://api.github.com/repos/jgraph/drawio-desktop/releases/latest | grep browser_download_url | grep '\.deb' | cut -d '"' -f 4 | wget -i -
  - apt -f install -y ./drawio-amd64-*.deb
  - pip install -r requirements.txt

mkdocs:
  stage: build
  variables:
    ENABLE_PDF_EXPORT: 1
  image: python:3.9-bullseye
  extends:
  - .install_dependencies
  script:
  - mkdocs build --verbose --site-dir site
  artifacts:
    paths:
    - site

pages:
  stage: deploy

  needs:
  - job: mkdocs
    artifacts: true

  script:
  - mkdir -p $DEPLOY_PATH
  - cp -a site/* $DEPLOY_PATH/

  artifacts:
    paths:
    - public

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      variables:
        DEPLOY_PATH: public/mr-$CI_MERGE_REQUEST_IID

    - if: $CI_PIPELINE_SOURCE  == 'push' && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        DEPLOY_PATH: public

preview-environment:
  stage: deploy
  needs:
    - pages

  environment:
    name: mr-$CI_MERGE_REQUEST_IID
    url: "$CI_PROJECT_URL/mr-$CI_MERGE_REQUEST_IID"
    auto_stop_in: 30 days

  script:
  - echo "$CI_PROJECT_URL/mr-$CI_MERGE_REQUEST_IID"

  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

production-environment:
  stage: deploy
  needs:
    - pages

  environment:
    name: production-gitlab
    url: $CI_PROJECT_URL

  script:
  - echo "$CI_PAGES_URL"

  rules:
    - if: $CI_PIPELINE_SOURCE  == 'push' && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH