repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
      - id: check-json
      - id: trailing-whitespace
        exclude_types:
          - markdown

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.32.2
  hooks:
  - id: markdownlint
    files: '^docs/'
- repo: local
  hooks:
  - id: mkbuild
    name: Build mkdocs site
    entry: bash -c 'ENABLE_PDF_EXPORT=1 mkdocs build'
    language: system