site_name: Deployment Pipeline Reference Architecture
repo_name: "aws-deployment-pipeline-reference-architecture"
repo_url: "https://github.com/aws-samples/aws-deployment-pipeline-reference-architecture"
docs_dir: "docs"
edit_uri: "edit/main/docs/"
copyright: Copyright © Amazon Web Services, Inc. and/or its affiliates. All rights reserved.
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - toc.integrate
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: 'index.md'
  - Application Pipeline:
    - Architecture: 'application-pipeline/index.md'
    - Reference Implementations:
      - CDK Pipeline: 'application-pipeline/ri-cdk-pipeline.md'
    - Additional Sources: 'application-pipeline/additional-sources.md'
  # - Compute Image Pipeline:
  #   - Architecture: 'compute-image-pipeline/index.md'
  # - Account Fleet Management Pipeline:
  #   - Architecture: 'account-fleet-management-pipeline/index.md'
  # - Machine Learning Pipeline:
  #   - Architecture: 'machine-learning-pipeline/index.md'
  # - Dynamic Configuration Deployment Pipeline:
  #   - Architecture: 'dynamic-configuration-deployment-pipeline/index.md'

markdown_extensions:
  - def_list
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.extra
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - mkdocs_graphviz
plugins:
  - search
  - codeinclude
  - drawio-exporter:
      drawio_args:
      - --no-sandbox
  - with-pdf:
      author: AWS Professional Services
      copyright: Copyright © Amazon Web Services, Inc. and/or its affiliates. All rights reserved.
      cover_subtitle: "September 2022"
      enabled_if_env: ENABLE_PDF_EXPORT
      ordered_chapter_level: 1

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-Z5XE517K9W